const BIJIRIS_SESSION_CONCERN_CATEGORIES = [
  {
    id: "toilet",
    label: "【トイレ・デリケートゾーンのお悩み】",
    options: [
      "咳、くしゃみ、大笑いした時に尿もれすることがある",
      "ジャンプや運動、重いものを持った時に尿もれすることがある",
      "急にトイレに行きたくなる、我慢できず間に合わないことがある",
      "トイレが近い・夜中に何度もトイレで起きる",
      "デリケートゾーンの違和感や乾燥が気になる",
      "便秘しやすい・お腹が張りやすい",
    ],
  },
  {
    id: "posture",
    label: "【姿勢・体型のお悩み】",
    options: [
      "姿勢が崩れやすい・猫背や反り腰が気になる",
      "下腹ぽっこりが気になる",
      "ヒップラインや骨盤まわりのゆるみが気になる",
      "産後の体型変化が気になる",
    ],
  },
  {
    id: "pain",
    label: "【痛み・めぐりのお悩み】",
    options: [
      "腰痛がある",
      "股関節や骨盤まわりに痛み・違和感がある",
      "冷えやむくみが気になる",
      "疲れやすい・眠りが浅い",
    ],
  },
  {
    id: "care",
    label: "【ビジリス（骨盤底筋ケア）について知りたいこと】",
    options: [
      "骨盤底筋ケアでどんな変化が期待できるか知りたい",
      "自宅でできる骨盤底筋ケアを知りたい",
      "妊活や産後ケアにどう役立つか知りたい",
      "自分に合う通い方や頻度を知りたい",
      "その他",
    ],
  },
];

function getBijirisSessionConcernOptions() {
  return BIJIRIS_SESSION_CONCERN_CATEGORIES.flatMap((category) => category.options);
}

function makeDefaultSurveys(timestamp = new Date().toISOString()) {
  return [
    {
      id: "survey_bijiris_session",
      title: "ビジリス施術アンケート",
      description: "ビジリス施術後の体感やお悩みをお聞かせください。",
      introMessage: "施術内容を選択後、本日の体感や気になることをご回答ください。",
      completionMessage: "ビジリス施術アンケートのご回答ありがとうございました。",
      status: "published",
      createdAt: timestamp,
      updatedAt: timestamp,
      questions: [
        {
          id: "q_bijiris_session_type",
          label: "施術内容",
          type: "choice",
          required: true,
          options: ["初回お試し", "回数券", "単発", "トライアル"],
        },
        {
          id: "q_bijiris_session_ticket_plan",
          label: "回数券の種類",
          type: "choice",
          required: true,
          options: ["6回券", "10回券"],
          visibleWhen: { questionId: "q_bijiris_session_type", value: "回数券" },
        },
        {
          id: "q_bijiris_session_feeling",
          label: "本日のビジリスの体感はいかがでしたか？　以前と比べて変化したことなどがあればご記載ください",
          type: "textarea",
          required: true,
          options: [],
        },
        {
          id: "q_bijiris_session_ticket_photos",
          label: "写真4枚（モニター時の写真2枚・回数券終了時の写真2枚）",
          type: "photo",
          required: true,
          options: [],
          visibleWhen: { questionId: "q_bijiris_session_type", value: "回数券" },
        },
        {
          id: "q_bijiris_session_concern",
          label:
            "普段のお身体のお悩みや、ビジリス（骨盤底筋ケア）について気になること・知りたいことはありますか？（複数選択可）",
          type: "checkbox",
          required: false,
          options: getBijirisSessionConcernOptions(),
        },
      ],
    },
    {
      id: "survey_bijiris_ticket_end",
      title: "ビジリス回数券終了アンケート",
      description: "回数券終了時点での体感や日常生活の変化をお聞かせください。",
      introMessage: "回数券終了時点での変化やご要望を確認し、今後のご案内に活用します。",
      completionMessage: "ビジリス回数券終了アンケートのご回答ありがとうございました。",
      status: "published",
      createdAt: timestamp,
      updatedAt: timestamp,
      questions: [
        {
          id: "q_ticket_end_feeling",
          label: "本日のビジリスの体感はいかがでしたか？",
          type: "textarea",
          required: true,
          options: [],
        },
        {
          id: "q_ticket_end_life_changes",
          label: "日常生活で変化を感じたことはありますか？（複数回答可）",
          type: "checkbox",
          required: false,
          options: [
            "立っている時や座っている時の姿勢が楽になった",
            "長時間歩いても疲れにくくなった",
            "ズボンやスカートが緩くなった気がする",
            "腰痛・股関節痛が軽くなった",
            "冷え性が良くなった（体がポカポカする）",
            "睡眠の質が良くなった",
            "階段の上り下りが楽になった",
            "便通が良くなった",
            "その他",
          ],
        },
        {
          id: "q_ticket_end_improve",
          label: "今後もっと改善したい部分はありますか？",
          type: "checkbox",
          required: false,
          options: [
            "もっとお腹周りを引き締めたい",
            "痛みのない生活を送りたい",
            "姿勢をもっと良くしたい",
            "今の良い状態をキープしたい",
            "トイレトラブルを改善したい",
            "睡眠の質を高めたい",
            "妊娠しやすい体づくりをしたい",
            "その他",
          ],
        },
        {
          id: "q_ticket_end_photo_first",
          label: "計測写真(1回目)",
          type: "photo",
          required: false,
          options: [],
        },
        {
          id: "q_ticket_end_photo_last",
          label: "計測写真(今回)",
          type: "photo",
          required: false,
          options: [],
        },
        {
          id: "q_ticket_end_consultation",
          label: "ご質問・ご相談(自由記述)",
          type: "textarea",
          required: false,
          options: [],
        },
        {
          id: "q_ticket_end_ticket_size",
          label: "回数券の種類",
          type: "choice",
          required: true,
          options: ["6回券", "10回券"],
        },
        {
          id: "q_ticket_end_ticket_sheet",
          label: "回数券の何枚目ですか？",
          type: "choice",
          required: true,
          options: [
            "1枚目",
            "2枚目",
            "3枚目",
            "4枚目",
            "5枚目",
            "6枚目",
            "7枚目",
            "8枚目",
            "9枚目",
            "10枚目",
          ],
        },
        {
          id: "q_ticket_end_ticket_round",
          label: "回数券の何回目ですか？",
          type: "choice",
          required: true,
          options: [
            "1回目",
            "2回目",
            "3回目",
            "4回目",
            "5回目",
            "6回目",
            "7回目",
            "8回目",
            "9回目",
            "10回目",
          ],
        },
      ],
    },
    {
      id: "survey_bijiris_monitor_end",
      title: "モニター終了アンケート",
      description: "モニター終了時点での体感、変化、今後のご希望をお聞かせください。",
      introMessage: "モニター終了時点での変化や今後のご希望を確認し、次のご提案に活用します。",
      completionMessage: "モニター終了アンケートのご回答ありがとうございました。",
      status: "published",
      createdAt: timestamp,
      updatedAt: timestamp,
      questions: [
        {
          id: "q_monitor_end_usage",
          label: "ビジリスの刺激や使用感はいかがでしたか？",
          type: "checkbox",
          required: true,
          options: [
            "痛気持ちよくて効いている感じがした",
            "最初は驚いたが慣れた",
            "リラックスして座っていられた",
            "その他",
          ],
        },
        {
          id: "q_monitor_end_life_changes",
          label: "ビジリスを6回体験して、日常生活で変化を感じたことはありますか？（複数回答可）",
          type: "checkbox",
          required: false,
          options: [
            "立っている時や座っている時の姿勢が楽になった",
            "長時間歩いても疲れにくくなった",
            "尿漏れや頻尿が気にならなくなった",
            "ズボンやスカートが緩くなった気がする",
            "冷え性が改善された（体がポカポカする）",
            "腰痛・股関節痛が軽くなった",
            "便通が良くなった",
            "睡眠の質が良くなった",
            "階段の上り下りが楽になった",
            "その他",
          ],
        },
        {
          id: "q_monitor_end_improve",
          label: "今後もっと改善したい部分はありますか？",
          type: "checkbox",
          required: false,
          options: [
            "もっとお腹周りを引き締めたい",
            "完全に痛みのない生活を送りたい",
            "姿勢をもっと良くしたい",
            "今の良い状態をキープしたい",
            "睡眠の質を高めたい",
            "トイレトラブルを改善したい",
            "妊娠しやすい体づくりをしたい",
            "骨盤底筋をもっと鍛えたい",
            "その他",
          ],
        },
        {
          id: "q_monitor_end_sns_permission",
          label: "今回の測定結果や感想を、個人が特定できない形でSNSや院内掲示に掲載させていただいてもよろしいでしょうか？",
          type: "choice",
          required: true,
          options: [
            "写真・数値・感想すべてOK",
            "数値・感想のみOK",
            "感想のみOK",
            "掲載不可",
          ],
        },
        {
          id: "q_monitor_end_photo_first",
          label: "計測写真(1回目)",
          type: "photo",
          required: false,
          options: [],
        },
        {
          id: "q_monitor_end_advice_sheet",
          label: "(任意)あなたの身体の変化を「見える化」！「ビフォーアフター写真＆個別アドバイスシート」をプレゼント",
          type: "choice",
          required: false,
          options: ["希望する", "希望しない"],
        },
        {
          id: "q_monitor_end_next",
          label: "今後はどうしていきたいですか？",
          type: "choice",
          required: true,
          options: [
            "6回の効果を無駄にしないために継続していきたい",
            "継続は考えていない",
            "迷っている",
            "その他",
          ],
        },
        {
          id: "q_monitor_end_plan",
          label: "継続していきたい方へ\n＊今後の継続プラン(回数券)について、ご希望のコースをお選びください",
          type: "choice",
          required: false,
          options: [
            "SNS掲載御礼！特別感謝コース（初回30%OFF）",
            "SNS掲載御礼！特別感謝コース（30%OFF）",
            "モニター様優待コース（10%OFF）",
            "その他",
          ],
          visibleWhen: {
            questionId: "q_monitor_end_next",
            value: "6回の効果を無駄にしないために継続していきたい",
          },
        },
        {
          id: "q_monitor_end_consultation",
          label: "ご質問・ご相談(自由記述)",
          type: "textarea",
          required: false,
          options: [],
        },
        {
          id: "q_monitor_end_photo_last",
          label: "計測写真(6回目)",
          type: "photo",
          required: false,
          options: [],
        },
      ],
    },
  ];
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { makeDefaultSurveys };
}

if (typeof window !== "undefined") {
  window.MayumiDefaultSurveys = makeDefaultSurveys;
}
