function makeDefaultSurveys(timestamp = new Date().toISOString()) {
  return [
    {
      id: "survey_bijiris_session",
      title: "ビジリス施術アンケート",
      description: "ビジリス施術後の体感やご相談内容をお聞かせください。",
      status: "published",
      createdAt: timestamp,
      updatedAt: timestamp,
      questions: [
        {
          id: "q_bijiris_session_consultation",
          label: "ご質問・ご相談",
          type: "textarea",
          required: false,
          options: [],
        },
        {
          id: "q_bijiris_session_feeling",
          label: "本日のビジリスの体感はいかがでしたか？",
          type: "textarea",
          required: true,
          options: [],
        },
        {
          id: "q_bijiris_session_type",
          label: "施術内容",
          type: "choice",
          required: true,
          options: ["モニター", "回数券", "乗り放題キャンペーン", "単発", "トライアル", "1~3回"],
        },
        {
          id: "q_bijiris_session_monitor_count",
          label: "モニターと答えた方へ",
          type: "choice",
          required: false,
          options: ["1回目", "2回目", "3回目", "4回目", "5回目", "6回目"],
        },
        {
          id: "q_bijiris_session_ticket_count",
          label: "回数券と答えた方へ",
          type: "choice",
          required: false,
          options: [
            "1回目",
            "2回目",
            "3回目",
            "4回目",
            "5回目",
            "6回目",
            "7回目",
            "8回目",
            "9回目",
            "10回目",
          ],
        },
        {
          id: "q_bijiris_session_unlimited",
          label: "乗り放題キャンペーンと答えた方へ",
          type: "text",
          required: false,
          options: [],
        },
        {
          id: "q_bijiris_session_single",
          label: "単発と答えた方へ",
          type: "text",
          required: false,
          options: [],
        },
        {
          id: "q_bijiris_session_trial",
          label: "トライアルと答えた方へ",
          type: "text",
          required: false,
          options: [],
        },
      ],
    },
    {
      id: "survey_bijiris_ticket_end",
      title: "ビジリス回数券終了アンケート",
      description: "回数券終了時点での体感や日常生活の変化をお聞かせください。",
      status: "published",
      createdAt: timestamp,
      updatedAt: timestamp,
      questions: [
        {
          id: "q_ticket_end_feeling",
          label: "本日のビジリスの体感はいかがでしたか？",
          type: "textarea",
          required: true,
          options: [],
        },
        {
          id: "q_ticket_end_life_changes",
          label: "日常生活で変化を感じたことはありますか？（複数回答可）",
          type: "checkbox",
          required: false,
          options: [
            "立っている時や座っている時の姿勢が楽になった",
            "長時間歩いても疲れにくくなった",
            "ズボンやスカートが緩くなった気がする",
            "腰痛・股関節痛が軽くなった",
            "冷え性が良くなった（体がポカポカする）",
            "睡眠の質が良くなった",
            "階段の上り下りが楽になった",
            "便通が良くなった",
            "その他",
          ],
        },
        {
          id: "q_ticket_end_improve",
          label: "今後もっと改善したい部分はありますか？",
          type: "checkbox",
          required: false,
          options: [
            "もっとお腹周りを引き締めたい",
            "痛みのない生活を送りたい",
            "姿勢をもっと良くしたい",
            "今の良い状態をキープしたい",
            "トイレトラブルを改善したい",
            "睡眠の質を高めたい",
            "妊娠しやすい体づくりをしたい",
            "その他",
          ],
        },
        {
          id: "q_ticket_end_photo_first",
          label: "計測写真(1回目)",
          type: "photo",
          required: false,
          options: [],
        },
        {
          id: "q_ticket_end_photo_last",
          label: "計測写真(6回目or10回目)",
          type: "photo",
          required: false,
          options: [],
        },
        {
          id: "q_ticket_end_consultation",
          label: "ご質問・ご相談(自由記述)",
          type: "textarea",
          required: false,
          options: [],
        },
        {
          id: "q_ticket_end_ticket_size",
          label: "回数券の枚数",
          type: "choice",
          required: true,
          options: ["6回券", "10回券"],
        },
      ],
    },
    {
      id: "survey_bijiris_monitor_end",
      title: "モニター終了アンケート",
      description: "モニター終了時点での体感、変化、今後のご希望をお聞かせください。",
      status: "published",
      createdAt: timestamp,
      updatedAt: timestamp,
      questions: [
        {
          id: "q_monitor_end_usage",
          label: "ビジリスの刺激や使用感はいかがでしたか？",
          type: "checkbox",
          required: true,
          options: [
            "痛気持ちよくて効いている感じがした",
            "最初は驚いたが慣れた",
            "リラックスして座っていられた",
            "その他",
          ],
        },
        {
          id: "q_monitor_end_life_changes",
          label: "ビジリスを6回体験して、日常生活で変化を感じたことはありますか？（複数回答可）",
          type: "checkbox",
          required: false,
          options: [
            "立っている時や座っている時の姿勢が楽になった",
            "長時間歩いても疲れにくくなった",
            "尿漏れや頻尿が気にならなくなった",
            "ズボンやスカートが緩くなった気がする",
            "冷え性が改善された（体がポカポカする）",
            "腰痛・股関節痛が軽くなった",
            "便通が良くなった",
            "睡眠の質が良くなった",
            "階段の上り下りが楽になった",
            "その他",
          ],
        },
        {
          id: "q_monitor_end_improve",
          label: "今後もっと改善したい部分はありますか？",
          type: "checkbox",
          required: false,
          options: [
            "もっとお腹周りを引き締めたい",
            "完全に痛みのない生活を送りたい",
            "姿勢をもっと良くしたい",
            "今の良い状態をキープしたい",
            "睡眠の質を高めたい",
            "トイレトラブルを改善したい",
            "妊娠しやすい体づくりをしたい",
            "骨盤底筋をもっと鍛えたい",
            "その他",
          ],
        },
        {
          id: "q_monitor_end_sns_permission",
          label: "今回の測定結果や感想を、個人が特定できない形でSNSや院内掲示に掲載させていただいてもよろしいでしょうか？",
          type: "choice",
          required: true,
          options: [
            "写真・数値・感想すべてOK",
            "数値・感想のみOK",
            "感想のみOK",
            "掲載不可",
          ],
        },
        {
          id: "q_monitor_end_photo_first",
          label: "計測写真(1回目)",
          type: "photo",
          required: false,
          options: [],
        },
        {
          id: "q_monitor_end_advice_sheet",
          label: "(任意)あなたの身体の変化を「見える化」！「ビフォーアフター写真＆個別アドバイスシート」をプレゼント",
          type: "choice",
          required: false,
          options: ["希望する", "希望しない"],
        },
        {
          id: "q_monitor_end_next",
          label: "今後はどうしていきたいですか？",
          type: "choice",
          required: true,
          options: [
            "6回の効果を無駄にしないために継続していきたい",
            "継続は考えていない",
            "迷っている",
            "その他",
          ],
        },
        {
          id: "q_monitor_end_plan",
          label: "継続していきたい方へ\n＊今後の継続プラン(回数券)について、ご希望のコースをお選びください",
          type: "choice",
          required: false,
          options: [
            "SNS掲載御礼！特別感謝コース（初回30%OFF）",
            "SNS掲載御礼！特別感謝コース（30%OFF）",
            "モニター様優待コース（10%OFF）",
            "その他",
          ],
        },
        {
          id: "q_monitor_end_consultation",
          label: "ご質問・ご相談(自由記述)",
          type: "textarea",
          required: false,
          options: [],
        },
        {
          id: "q_monitor_end_photo_last",
          label: "計測写真(6回目)",
          type: "photo",
          required: false,
          options: [],
        },
      ],
    },
  ];
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { makeDefaultSurveys };
}

if (typeof window !== "undefined") {
  window.MayumiDefaultSurveys = makeDefaultSurveys;
}
